### ISSUE TITLE
A little bug regarding a consonant+'ch'

### ISSUE THREAD

**Issue by MdeHpy** [jdevera/pylabeador#11]
Hello there,

I think that I spotted a bug in the fantastic pylabeador program. I'll write some self-explaining examples below where you can appreciate that it does not manage the 'ch' in the right way if it is preceded by a consonant.

>>> pylabeador.syllabify('jarcha')
['jarc', 'ha']
>>> pylabeador.syllabify('parche')
['parc', 'he']
>>> pylabeador.syllabify('elche')
['elc', 'he']
>>> pylabeador.syllabify('colcha')
['colc', 'ha']
>>> pylabeador.syllabify('deschapar')
['desc', 'ha', 'par']

Again, thank you for your effort and congratulations for such an interesting work.

M

**Comment by jdevera** [comment]
Thank you for using pylabeador and for taking the time to report this to help make it better.

That was an outstanding catch! I made a mistake when adapting the original algorithm, it seems. The issue is now solved, and I have published version 0.4.0 with the fix.
